# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table_info = QtWidgets.QTableWidget(self.centralwidget)
        self.table_info.setGeometry(QtCore.QRect(20, 90, 761, 231))
        self.table_info.setObjectName("table_info")
        self.table_info.setColumnCount(7)
        self.table_info.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(6, item)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 340, 761, 221))
        self.textEdit.setObjectName("textEdit")
        self.rb_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1.setEnabled(True)
        self.rb_1.setGeometry(QtCore.QRect(80, 120, 89, 16))
        self.rb_1.setText("")
        self.rb_1.setAutoRepeat(False)
        self.rb_1.setAutoExclusive(False)
        self.rb_1.setObjectName("rb_1")
        self.rb_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_2.setEnabled(True)
        self.rb_2.setGeometry(QtCore.QRect(80, 150, 89, 16))
        self.rb_2.setText("")
        self.rb_2.setAutoRepeat(False)
        self.rb_2.setAutoExclusive(False)
        self.rb_2.setObjectName("rb_2")
        self.rb_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_3.setEnabled(True)
        self.rb_3.setGeometry(QtCore.QRect(80, 180, 89, 16))
        self.rb_3.setText("")
        self.rb_3.setAutoRepeat(False)
        self.rb_3.setAutoExclusive(False)
        self.rb_3.setObjectName("rb_3")
        self.rb_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_4.setEnabled(True)
        self.rb_4.setGeometry(QtCore.QRect(80, 210, 89, 16))
        self.rb_4.setText("")
        self.rb_4.setAutoRepeat(False)
        self.rb_4.setAutoExclusive(False)
        self.rb_4.setObjectName("rb_4")
        self.rb_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_5.setEnabled(True)
        self.rb_5.setGeometry(QtCore.QRect(80, 240, 89, 16))
        self.rb_5.setText("")
        self.rb_5.setAutoRepeat(False)
        self.rb_5.setAutoExclusive(False)
        self.rb_5.setObjectName("rb_5")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(20, 10, 91, 61))
        self.btn_start.setObjectName("btn_start")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(640, 120, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table_info.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_info.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_info.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_info.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table_info.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.table_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "准备"))
        item = self.table_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "用户名"))
        item = self.table_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "密码"))
        item = self.table_info.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "平台"))
        item = self.table_info.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "分类"))
        item = self.table_info.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "广告语"))
        item = self.table_info.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "进度"))
        self.btn_start.setText(_translate("MainWindow", "开始"))

